### ISSUE TITLE
illegal memory access

### ISSUE THREAD

**Issue by jinz2014** [leefige/radik#1]
Please take a look at the following:

nvcc -O3 -arch=sm_80 test_radik.cu -lcurand

Please enter BATCHSIZE:
16
Please enter power of N(max val 29):
29
Please enter K:
512
Please enter RANDOM_TASK:
0-each task length in this batch will be N
1-each task length in this batch will fluctuate randomly between 0.9 * N and 1.1 * N
0
Please choose whether scaling or not (0: N, 1: Y)
0
batchSize: 16, K: 512
[0, 536870912]
[1, 536870912]
[2, 536870912]
[3, 536870912]
[4, 536870912]
[5, 536870912]
[6, 536870912]
[7, 536870912]
[8, 536870912]
[9, 536870912]
[10, 536870912]
[11, 536870912]
[12, 536870912]
[13, 536870912]
[14, 536870912]
[15, 536870912]
terminate called after throwing an instance of 'std::runtime_error'
  what():  cuda call failed (700) at topk_radixselect.h:150 : an illegal memory access was encountered

Aborted (core dumped)

**Comment by leefige** [comment]
I believe this is due to GPU OOM. Please try with smaller batch sizes or smaller N.

Unfortunately, the test codes did not check the return status of CUDA malloc. This has been fixed in #4
